# Generated by Django 2.2.5 on 2019-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_parseddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownmodel',
            name='cities',
            field=models.CharField(default='green', max_length=6),
        ),
    ]
