# Generated by Django 2.2.5 on 2019-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190908_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownmodel',
            name='cities',
            field=models.CharField(choices=[('Toronto', 'Toronto'), ('New york', 'New york'), ('Montreal', 'Montreal'), ('Ottawa', 'Ottawa')], default='green', max_length=6),
        ),
    ]
